//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Man_Sor_V_AEntities5 : DbContext
    {
        public Man_Sor_V_AEntities5()
            : base("name=Man_Sor_V_AEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Activ_user> Activ_user { get; set; }
        public virtual DbSet<Blok_pitanie> Blok_pitanie { get; set; }
        public virtual DbSet<Kabeli> Kabeli { get; set; }
        public virtual DbSet<Klaviatyra> Klaviatyra { get; set; }
        public virtual DbSet<Korpusa> Korpusa { get; set; }
        public virtual DbSet<Kovriki> Kovriki { get; set; }
        public virtual DbSet<Mat_plat> Mat_plat { get; set; }
        public virtual DbSet<Monitors> Monitors { get; set; }
        public virtual DbSet<Mouse> Mouse { get; set; }
        public virtual DbSet<Nayshniki> Nayshniki { get; set; }
        public virtual DbSet<Notebok> Notebok { get; set; }
        public virtual DbSet<Operativka> Operativka { get; set; }
        public virtual DbSet<Oxladd> Oxladd { get; set; }
        public virtual DbSet<Procesor> Procesor { get; set; }
        public virtual DbSet<Ssd_and_Hdd> Ssd_and_Hdd { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Veb_camera> Veb_camera { get; set; }
        public virtual DbSet<Videocart> Videocart { get; set; }
        public virtual DbSet<Vneshnie_nakopiteli> Vneshnie_nakopiteli { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
