//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kabeli
    {
        public int id_kabeli { get; set; }
        public string Model { get; set; }
        public string Connector_1 { get; set; }
        public string Connector_2 { get; set; }
        public int Zena { get; set; }
        public int Kolichestvo { get; set; }
        public string Dlina_M_ { get; set; }
        public string Image { get; set; }
    }
}
