//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korpusa
    {
        public int Id_korpusa { get; set; }
        public string Nazvanie { get; set; }
        public string Tiporazmer { get; set; }
        public string FormFactor { get; set; }
        public int Zena { get; set; }
        public int Kolichestvo { get; set; }
        public string Image { get; set; }
    }
}
