//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mat_plat
    {
        public int Id_Mat_plat { get; set; }
        public string Name_Mat_plat { get; set; }
        public string Form_factor { get; set; }
        public string Coket { get; set; }
        public string ChipSet { get; set; }
        public int Kolvo_pamati { get; set; }
        public int Zena { get; set; }
        public int Kolichestvo { get; set; }
        public string Image { get; set; }
    }
}
