//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nayshniki
    {
        public int id_nayshniki { get; set; }
        public string Model { get; set; }
        public string Tip { get; set; }
        public string Dlina { get; set; }
        public string Vid_peredachi { get; set; }
        public int Zena { get; set; }
        public int Kolichestvo { get; set; }
        public string Image { get; set; }
    }
}
