//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notebok
    {
        public int id_notebok { get; set; }
        public string Model { get; set; }
        public string Volume_operativ { get; set; }
        public string procesor { get; set; }
        public string Zena { get; set; }
        public string Kolichectvo { get; set; }
        public string Pamat { get; set; }
        public string Image { get; set; }
    }
}
