//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oxladd
    {
        public int Id_oxlad { get; set; }
        public string Name_oxlad { get; set; }
        public int Oborotov_min { get; set; }
        public string Power { get; set; }
        public int Zena { get; set; }
        public int Kolishestvo { get; set; }
        public string Image { get; set; }
    }
}
