//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesor
    {
        public int Id_procesor { get; set; }
        public string Name_procesor { get; set; }
        public string Coket { get; set; }
        public int Chislo_yader { get; set; }
        public int Chislo_potokov { get; set; }
        public int Zena { get; set; }
        public int Kolishestvo { get; set; }
        public string Image { get; set; }
    }
}
