//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ssd_and_Hdd
    {
        public int Id_SSD_HDD { get; set; }
        public string Name_SSD_HDD { get; set; }
        public string volume { get; set; }
        public int reading_speed { get; set; }
        public int write_speed { get; set; }
        public int Zena { get; set; }
        public int Kolishestvo { get; set; }
        public string Image { get; set; }
    }
}
