//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videocart
    {
        public int Id_videocart { get; set; }
        public string Name_videocart { get; set; }
        public string Castota_yadra { get; set; }
        public string Tip_pamati { get; set; }
        public string Obem_pamati { get; set; }
        public int Zena { get; set; }
        public int Kolichestvo { get; set; }
        public string Image { get; set; }
    }
}
