//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vneshnie_nakopiteli
    {
        public int id_vneshnie_nakopiteli { get; set; }
        public string Model { get; set; }
        public string Volume { get; set; }
        public string Connect { get; set; }
        public string Write_speed { get; set; }
        public string Read_speed { get; set; }
        public int Zena { get; set; }
        public int Kolichestvo { get; set; }
        public string Image { get; set; }
    }
}
