//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Id_zakaz { get; set; }
        public string Users { get; set; }
        public string Nazvanie { get; set; }
        public string Zena { get; set; }
        public string Image { get; set; }
    }
}
